export const TOGGLE_PROGRESS = "TOGGLE_PROGRESS";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const LOG_OUT = "LOG_OUT";
export const STORE_USER = "STORE_USER";
//courses
export const FETCH_COURSES_BEGIN = "FETCH_COURSES_BEGIN";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

export const FETCH_COURSE_CONTENTS_BEGIN = "FETCH_COURSE_CONTENTS_BEGIN";
export const FETCH_COURSE_CONTENTS_SUCCESS = "FETCH_COURSE_CONTENTS_SUCCESS";
export const FETCH_COURSE_CONTENTS_FAILURE = "FETCH_COURSE_CONTENTS_FAILURE";

export const FETCH_VIDEOS_BEGIN = "FETCH_VIDEOS_BEGIN";
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";

export const FETCH_PDFS_BEGIN = "FETCH_PDFS_BEGIN";
export const FETCH_PDFS_SUCCESS = "FETCH_PDFS_SUCCESS";
export const FETCH_PDFS_FAILURE = "FETCH_PDFS_FAILURE";

export const FETCH_LINKS_BEGIN = "FETCH_LINKS_BEGIN";
export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
export const FETCH_LINKS_FAILURE = "FETCH_LINKS_FAILURE";

export const CLEAR_COURSES = "CLEAR_COURSES";
export const SET_SELECTED_COURSE = "SET_SELECTED_COURSE";
export const SET_SELECTED_COURSE_CONTENT = "SET_SELECTED_COURSE_CONTENT";
export const SET_SELECTED_VIDEO = "SET_SELECTED_VIDEO";
export const SET_SELECTED_PDF = "SET_SELECTED_PDF";
export const SET_SELECTED_LINK = "SET_SELECTED_LINK";

export const SET_DOWNLOAD_URL = "SET_DOWNLOAD_URL";
