export const TOGGLE_PROGRESS = "TOGGLE_PROGRESS";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const LOG_OUT = "LOG_OUT";
export const STORE_USER = "STORE_USER";
//courses
export const FETCH_COURSES_BEGIN = "FETCH_COURSES_BEGIN";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

export const FETCH_COURSE_CONTENTS_BEGIN = "FETCH_COURSE_CONTENTS_BEGIN";
export const FETCH_COURSE_CONTENTS_SUCCESS = "FETCH_COURSE_CONTENTS_SUCCESS";
export const FETCH_COURSE_CONTENTS_FAILURE = "FETCH_COURSE_CONTENTS_FAILURE";

export const CLEAR_COURSES = "CLEAR_COURSES";
export const SET_SELECTED_COURSE = "SET_SELECTED_COURSE";
export const SET_SELECTED_COURSE_CONTENT = "SET_SELECTED_COURSE_CONTENT";
